name: cuca
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

dependencies:
  # 基础系统依赖
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-include=2023.1.0=h06a4308_46344
  
  # Python环境
  - python=3.9.20=he870216_1
  - pip=24.2=py39h06a4308_0
  - setuptools=75.1.0=py39h06a4308_0
  - wheel=0.44.0=py39h06a4308_0
  
  # 系统库
  - openssl=3.0.15=h5eee18b_0
  - ca-certificates=2024.9.24=h06a4308_0
  - libgcc-ng=14.2.0=h69a702a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libffi=3.4.4=h6a678d5_1
  - zlib=1.2.13=h4ab18f5_6
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - ncurses=6.4=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - bzip2=1.0.8=h5eee18b_6
  - xz=5.4.6=h5eee18b_1
  
  # 图像处理库
  - pillow=11.0.0=py39hfdbf927_0
  - openjpeg=2.5.2=he7f1fd0_0
  - jpeg=9e=h5eee18b_3
  - libtiff=4.5.1=h6a678d5_0
  - lcms2=2.12=h3be6417_0
  - openslide=3.4.1=h7773abc_6
  - openslide-python=1.3.1=py39hd1e30aa_1
  
  # 开发工具
  - cython=3.0.11=py39h5eee18b_0
  - ninja=1.12.1=h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_0
  - cryptography=43.0.3=py39h7825ff9_1
  
  # Jupyter生态系统
  - jupyter=1.1.1
  - jupyterlab=4.2.6
  - notebook=7.2.2
  - ipython=8.15.0=py39h06a4308_0
  - ipykernel=6.29.5=py39h06a4308_0
  - ipywidgets=8.1.5
  
  # 数据处理基础包
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.2
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - h5py=3.12.1

  # 标记需要安装pip包
  - pip

prefix: /opt/conda